import { Product, Category, Order, Review } from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Tiểu thuyết",
    slug: "tieu-thuyet",
    imageUrl: "https://picsum.photos/seed/novel-books-forest/600/400",
    count: 284,
    subcategories: [
      { name: "Văn học Việt Nam", slug: "van-hoc-viet-nam" },
      { name: "Văn học nước ngoài", slug: "van-hoc-nuoc-ngoai" },
      { name: "Trinh thám", slug: "trinh-tham" },
      { name: "Khoa học viễn tưởng", slug: "khoa-hoc-vien-tuong" },
    ],
  },
  {
    id: "2",
    name: "Kỹ năng sống",
    slug: "ky-nang-song",
    imageUrl: "https://picsum.photos/seed/selfhelp-books-desk/600/400",
    count: 156,
    subcategories: [
      { name: "Phát triển bản thân", slug: "phat-trien-ban-than" },
      { name: "Kinh doanh & Lãnh đạo", slug: "kinh-doanh" },
      { name: "Tâm lý học", slug: "tam-ly-hoc" },
      { name: "Tài chính cá nhân", slug: "tai-chinh" },
    ],
  },
  {
    id: "3",
    name: "Sổ tay & Nhật ký",
    slug: "so-tay",
    imageUrl: "https://picsum.photos/seed/notebook-leather-journal/600/400",
    count: 93,
    subcategories: [
      { name: "Sổ da cao cấp", slug: "so-da" },
      { name: "Bullet Journal", slug: "bullet-journal" },
      { name: "Sổ kẻ ngang", slug: "so-ke-ngang" },
      { name: "Sketchbook", slug: "sketchbook" },
    ],
  },
  {
    id: "4",
    name: "Bút cao cấp",
    slug: "but-cao-cap",
    imageUrl: "https://picsum.photos/seed/premium-pens-stationery/600/400",
    count: 71,
    subcategories: [
      { name: "Bút máy", slug: "but-may" },
      { name: "Bút bi cao cấp", slug: "but-bi" },
      { name: "Bút dạ quang", slug: "but-da-quang" },
      { name: "Bộ dụng cụ viết", slug: "bo-dung-cu" },
    ],
  },
  {
    id: "5",
    name: "Thiếu nhi",
    slug: "thieu-nhi",
    imageUrl: "https://picsum.photos/seed/children-colorful-books/600/400",
    count: 198,
    subcategories: [
      { name: "Truyện tranh", slug: "truyen-tranh" },
      { name: "Khoa học cho bé", slug: "khoa-hoc-be" },
      { name: "Sách tô màu", slug: "sach-to-mau" },
    ],
  },
  {
    id: "6",
    name: "Quà tặng",
    slug: "qua-tang",
    imageUrl: "https://picsum.photos/seed/gift-stationery-set/600/400",
    count: 47,
    subcategories: [
      { name: "Bộ quà tặng văn phòng", slug: "qua-tang-van-phong" },
      { name: "Set bút + sổ", slug: "set-but-so" },
      { name: "Hộp quà đặc biệt", slug: "hop-qua" },
    ],
  },
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "the-great-gatsby-fitzgerald",
    name: "Gatsby Vĩ Đại",
    author: "F. Scott Fitzgerald",
    price: 89000,
    originalPrice: 120000,
    rating: 4.8,
    reviewCount: 342,
    category: "Tiểu thuyết",
    subcategory: "Văn học nước ngoài",
    imageUrl: "https://picsum.photos/seed/gatsby-novel-cover/400/560",
    images: [
      "https://picsum.photos/seed/gatsby-novel-cover/800/1120",
      "https://picsum.photos/seed/gatsby-novel-open/800/600",
      "https://picsum.photos/seed/gatsby-novel-back/400/560",
      "https://picsum.photos/seed/gatsby-novel-spine/200/560",
    ],
    badge: "Bestseller",
    description:
      "Gatsby Vĩ Đại là tiểu thuyết nổi tiếng nhất của F. Scott Fitzgerald, một trong những tác phẩm vĩ đại nhất của văn học Mỹ thế kỷ 20. Câu chuyện xoay quanh Jay Gatsby bí ẩn và tình yêu của ông dành cho Daisy Buchanan tươi đẹp. Tác phẩm là bức tranh sống động về thời đại Jazz và giấc mơ Mỹ.",
    specs: {
      pages: 218,
      size: "14 x 20.5 cm",
      publisher: "NXB Văn học",
      language: "Tiếng Việt",
      weight: "280g",
    },
    coverType: "Bìa mềm",
    inStock: true,
    tags: ["classic", "american-literature", "love", "society"],
  },
  {
    id: "p2",
    slug: "atomic-habits-clear",
    name: "Thói Quen Nguyên Tử",
    author: "James Clear",
    price: 129000,
    originalPrice: 168000,
    rating: 4.9,
    reviewCount: 891,
    category: "Kỹ năng sống",
    subcategory: "Phát triển bản thân",
    imageUrl: "https://picsum.photos/seed/atomic-habits-book/400/560",
    images: [
      "https://picsum.photos/seed/atomic-habits-book/800/1120",
      "https://picsum.photos/seed/atomic-habits-open-pages/800/600",
      "https://picsum.photos/seed/atomic-habits-back/400/560",
    ],
    badge: "Hot",
    description:
      "Thói Quen Nguyên Tử cung cấp một khung thực tế và đã được chứng minh để hình thành những thói quen tốt, phá vỡ những thói quen xấu và nắm vững những hành vi nhỏ dẫn đến kết quả đáng kinh ngạc.",
    specs: {
      pages: 356,
      size: "15.5 x 23 cm",
      publisher: "NXB Lao Động",
      language: "Tiếng Việt",
      weight: "380g",
    },
    coverType: "Bìa cứng",
    inStock: true,
    tags: ["habits", "self-improvement", "productivity"],
  },
  {
    id: "p3",
    slug: "leuchtturm-a5-notebook",
    name: "Sổ Leuchtturm1917 A5",
    author: "Leuchtturm1917",
    price: 285000,
    originalPrice: 340000,
    rating: 4.7,
    reviewCount: 187,
    category: "Sổ tay & Nhật ký",
    subcategory: "Bullet Journal",
    imageUrl: "https://picsum.photos/seed/leuchtturm-notebook-green/400/560",
    images: [
      "https://picsum.photos/seed/leuchtturm-notebook-green/800/1120",
      "https://picsum.photos/seed/leuchtturm-open-dotted/800/600",
      "https://picsum.photos/seed/leuchtturm-elastic-band/400/560",
    ],
    badge: "New",
    description:
      "Sổ Leuchtturm1917 A5 dotted - tiêu chuẩn vàng cho Bullet Journal. 249 trang dotted grid, đánh số trang, mục lục, 2 dấu trang ribbon, túi giấy bên trong và nhãn dán. Giấy 80g/m² không thấm mực.",
    specs: {
      pages: 249,
      size: "14.5 x 21 cm",
      publisher: "Leuchtturm1917",
      language: "Không áp dụng",
      weight: "420g",
      material: "Bìa cứng vải",
    },
    inStock: true,
    tags: ["bullet-journal", "dotted", "premium", "planner"],
  },
  {
    id: "p4",
    slug: "pilot-metropolitan-pen",
    name: "Bút Máy Pilot Metropolitan",
    author: "Pilot",
    price: 420000,
    originalPrice: 520000,
    rating: 4.6,
    reviewCount: 94,
    category: "Bút cao cấp",
    subcategory: "Bút máy",
    imageUrl: "https://picsum.photos/seed/pilot-fountain-pen-gold/400/560",
    images: [
      "https://picsum.photos/seed/pilot-fountain-pen-gold/800/1120",
      "https://picsum.photos/seed/pilot-pen-writing-paper/800/600",
      "https://picsum.photos/seed/pilot-pen-box/400/400",
    ],
    badge: "Sale",
    description:
      "Bút máy Pilot Metropolitan - dòng sản phẩm cao cấp dành cho người mới bắt đầu và chuyên nghiệp. Thân bút kim loại nặng tạo cảm giác viết thoải mái. Ngòi thép không gỉ cỡ M cho nét chữ mượt mà.",
    specs: {
      size: "13.7 cm (đóng), 15 cm (mở)",
      weight: "22g",
      material: "Thân kim loại, ngòi thép",
    },
    inStock: true,
    tags: ["fountain-pen", "pilot", "metal", "beginner"],
  },
  {
    id: "p5",
    slug: "sapiens-harari",
    name: "Lược Sử Loài Người",
    author: "Yuval Noah Harari",
    price: 148000,
    originalPrice: 185000,
    rating: 4.8,
    reviewCount: 1243,
    category: "Kỹ năng sống",
    subcategory: "Tâm lý học",
    imageUrl: "https://picsum.photos/seed/sapiens-book-cover/400/560",
    images: [
      "https://picsum.photos/seed/sapiens-book-cover/800/1120",
      "https://picsum.photos/seed/sapiens-open-page/800/600",
    ],
    badge: "Bestseller",
    description:
      "Một cuộc hành trình đầy hấp dẫn qua lịch sử nhân loại từ sự xuất hiện của loài người thông minh tại Đông Phi cách đây 100.000 năm đến thế giới hiện đại ngày nay.",
    specs: {
      pages: 512,
      size: "15 x 23 cm",
      publisher: "NXB Tri Thức",
      language: "Tiếng Việt",
      weight: "520g",
    },
    coverType: "Bìa mềm",
    inStock: true,
    tags: ["history", "humanity", "anthropology", "science"],
  },
  {
    id: "p6",
    slug: "muji-recycled-notebook",
    name: "Sổ Tái Chế MUJI A6",
    author: "MUJI",
    price: 65000,
    originalPrice: 85000,
    rating: 4.4,
    reviewCount: 312,
    category: "Sổ tay & Nhật ký",
    subcategory: "Sổ kẻ ngang",
    imageUrl: "https://picsum.photos/seed/muji-notebook-minimal/400/560",
    images: [
      "https://picsum.photos/seed/muji-notebook-minimal/800/1120",
      "https://picsum.photos/seed/muji-notebook-white-pages/800/600",
    ],
    badge: "New",
    description:
      "Sổ tái chế MUJI A6 với giấy kraft tái chế thân thiện môi trường. Thiết kế tối giản đặc trưng của MUJI. 80 trang kẻ ngang, bìa mềm.",
    specs: {
      pages: 80,
      size: "10.5 x 14.8 cm",
      publisher: "MUJI",
      language: "Không áp dụng",
      weight: "90g",
      material: "Giấy tái chế",
    },
    inStock: true,
    tags: ["muji", "minimal", "eco", "lined"],
  },
  {
    id: "p7",
    slug: "hoang-tu-be",
    name: "Hoàng Tử Bé",
    author: "Antoine de Saint-Exupéry",
    price: 58000,
    originalPrice: 75000,
    rating: 4.9,
    reviewCount: 2156,
    category: "Tiểu thuyết",
    subcategory: "Văn học nước ngoài",
    imageUrl: "https://picsum.photos/seed/little-prince-book/400/560",
    images: [
      "https://picsum.photos/seed/little-prince-book/800/1120",
      "https://picsum.photos/seed/little-prince-illustrations/800/600",
    ],
    badge: "Bestseller",
    description:
      "Hoàng Tử Bé - cuốn sách bán chạy nhất thế giới sau Kinh Thánh. Câu chuyện tuyệt đẹp về tình bạn, tình yêu và bản chất con người.",
    specs: {
      pages: 112,
      size: "13 x 19 cm",
      publisher: "NXB Hội Nhà Văn",
      language: "Tiếng Việt",
      weight: "160g",
    },
    coverType: "Bìa mềm",
    inStock: true,
    tags: ["classic", "philosophy", "children", "illustrated"],
  },
  {
    id: "p8",
    slug: "zebra-sarasa-set",
    name: "Set Bút Gel Zebra Sarasa",
    author: "Zebra",
    price: 185000,
    originalPrice: 230000,
    rating: 4.7,
    reviewCount: 428,
    category: "Bút cao cấp",
    subcategory: "Bộ dụng cụ viết",
    imageUrl: "https://picsum.photos/seed/zebra-sarasa-pens-colorful/400/560",
    images: [
      "https://picsum.photos/seed/zebra-sarasa-pens-colorful/800/1120",
      "https://picsum.photos/seed/zebra-pens-writing/800/600",
    ],
    badge: "Sale",
    description:
      "Set 10 màu bút gel Zebra Sarasa Clip 0.5mm. Mực gel nhanh khô, không lem, màu sắc rực rỡ. Kẹp bút tiện dụng, thân bút nhựa nhẹ.",
    specs: {
      weight: "120g (cả hộp)",
      material: "Ngòi thép không gỉ",
    },
    inStock: true,
    tags: ["gel-pen", "zebra", "colorful", "set"],
  },
  {
    id: "p9",
    slug: "dac-nhan-tam",
    name: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    price: 79000,
    originalPrice: 108000,
    rating: 4.7,
    reviewCount: 3241,
    category: "Kỹ năng sống",
    subcategory: "Phát triển bản thân",
    imageUrl: "https://picsum.photos/seed/dac-nhan-tam-cover/400/560",
    images: [
      "https://picsum.photos/seed/dac-nhan-tam-cover/800/1120",
      "https://picsum.photos/seed/dac-nhan-tam-inside/800/600",
    ],
    badge: "Bestseller",
    description:
      "Cuốn sách kỹ năng giao tiếp bán chạy nhất mọi thời đại. Dale Carnegie chỉ ra bí quyết giúp con người trở nên được yêu thích, thuyết phục người khác và tạo dựng mối quan hệ thành công.",
    specs: {
      pages: 320,
      size: "14.5 x 20.5 cm",
      publisher: "NXB Tổng hợp TP.HCM",
      language: "Tiếng Việt",
      weight: "340g",
    },
    coverType: "Bìa mềm",
    inStock: true,
    tags: ["communication", "influence", "self-help", "classic"],
  },
  {
    id: "p10",
    slug: "pentel-energel-set",
    name: "Bút Gel Pentel EnerGel",
    author: "Pentel",
    price: 95000,
    originalPrice: 120000,
    rating: 4.5,
    reviewCount: 176,
    category: "Bút cao cấp",
    subcategory: "Bút bi cao cấp",
    imageUrl: "https://picsum.photos/seed/pentel-energel-black/400/560",
    images: [
      "https://picsum.photos/seed/pentel-energel-black/800/1120",
      "https://picsum.photos/seed/pentel-pen-writing-close/800/600",
    ],
    badge: "New",
    description:
      "Bút gel Pentel EnerGel 0.5mm - dòng bút nổi tiếng với mực gel khô cực nhanh chỉ trong 0.4 giây. Không lem khi viết tay, thân bút nhẹ thoải mái.",
    specs: {
      weight: "15g",
      material: "Thân nhựa cao cấp",
    },
    inStock: true,
    tags: ["gel-pen", "pentel", "quick-dry"],
  },
  {
    id: "p11",
    slug: "rich-dad-poor-dad",
    name: "Cha Giàu Cha Nghèo",
    author: "Robert T. Kiyosaki",
    price: 109000,
    originalPrice: 145000,
    rating: 4.6,
    reviewCount: 2847,
    category: "Kỹ năng sống",
    subcategory: "Tài chính cá nhân",
    imageUrl: "https://picsum.photos/seed/rich-dad-poor-dad-vi/400/560",
    images: [
      "https://picsum.photos/seed/rich-dad-poor-dad-vi/800/1120",
      "https://picsum.photos/seed/rich-dad-open-pages/800/600",
    ],
    badge: "Bestseller",
    description:
      "Cuốn sách tài chính cá nhân bán chạy nhất thế giới trong 6 năm liền. Robert Kiyosaki chia sẻ triết lý tài chính và cách người giàu tư duy về tiền bạc khác với người nghèo.",
    specs: {
      pages: 358,
      size: "14.5 x 20.5 cm",
      publisher: "NXB Lao Động",
      language: "Tiếng Việt",
      weight: "380g",
    },
    coverType: "Bìa mềm",
    inStock: true,
    tags: ["finance", "investment", "wealth", "mindset"],
  },
  {
    id: "p12",
    slug: "traveler-notebook-brass",
    name: "Traveler's Notebook Đồng",
    author: "Traveler's Company",
    price: 680000,
    originalPrice: 820000,
    rating: 4.9,
    reviewCount: 43,
    category: "Sổ tay & Nhật ký",
    subcategory: "Sổ da cao cấp",
    imageUrl: "https://picsum.photos/seed/travelers-notebook-leather/400/560",
    images: [
      "https://picsum.photos/seed/travelers-notebook-leather/800/1120",
      "https://picsum.photos/seed/travelers-notebook-open/800/600",
      "https://picsum.photos/seed/travelers-notebook-accessories/800/400",
    ],
    badge: "New",
    description:
      "Traveler's Notebook phiên bản Brass Limited Edition. Bìa da bò thật được thuộc theo phương pháp truyền thống, mỗi cuốn có vân độc nhất. Bộ refill thay thế tiện lợi.",
    specs: {
      size: "22 x 12 cm",
      weight: "340g",
      material: "Da bò thật",
      publisher: "Traveler's Company Japan",
    },
    inStock: true,
    tags: ["leather", "traveler", "premium", "limited"],
  },
];

export const orders: Order[] = [
  {
    id: "DH-2025-0041",
    date: "12/07/2025",
    status: "Đã giao",
    items: [
      { name: "Thói Quen Nguyên Tử", quantity: 1, price: 129000 },
      { name: "Sổ Leuchtturm1917 A5", quantity: 2, price: 285000 },
    ],
    total: 699000,
    shippingAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
  },
  {
    id: "DH-2025-0038",
    date: "28/06/2025",
    status: "Đã giao",
    items: [
      { name: "Lược Sử Loài Người", quantity: 1, price: 148000 },
      { name: "Bút Máy Pilot Metropolitan", quantity: 1, price: 420000 },
    ],
    total: 568000,
    shippingAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
  },
  {
    id: "DH-2025-0051",
    date: "10/07/2025",
    status: "Đang giao",
    items: [
      { name: "Gatsby Vĩ Đại", quantity: 1, price: 89000 },
      { name: "Set Bút Gel Zebra Sarasa", quantity: 1, price: 185000 },
    ],
    total: 274000,
    shippingAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
  },
  {
    id: "DH-2025-0055",
    date: "14/07/2025",
    status: "Đang xử lý",
    items: [
      { name: "Traveler's Notebook Đồng", quantity: 1, price: 680000 },
    ],
    total: 680000,
    shippingAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    author: "Nguyễn Minh Châu",
    rating: 5,
    date: "08/07/2025",
    comment:
      "Sách được đóng gói cẩn thận, chất lượng in ấn tốt. Giao nhanh hơn dự kiến. Rất hài lòng với dịch vụ của Trang.",
    helpful: 23,
  },
  {
    id: "r2",
    author: "Trần Anh Tuấn",
    rating: 5,
    date: "02/07/2025",
    comment:
      "Bản dịch rất sát nghĩa, dễ đọc. Bìa sách đẹp, giấy không quá mỏng. Sẽ tiếp tục ủng hộ shop.",
    helpful: 17,
  },
  {
    id: "r3",
    author: "Lê Phương Thảo",
    rating: 4,
    date: "25/06/2025",
    comment:
      "Cuốn sách hay, nội dung phong phú. Chỉ tiếc bìa hơi dễ bị nhăn khi vận chuyển. Vẫn rất đáng mua.",
    helpful: 9,
  },
];

export const heroSlides = [
  {
    id: 1,
    eyebrow: "Bộ sưu tập mùa hè 2025",
    headline: "Sách hay cho\nngày hè tươi sáng",
    subtext: "Khám phá hơn 3.000 đầu sách và văn phòng phẩm cao cấp",
    cta: "Khám phá ngay",
    imageUrl: "https://picsum.photos/seed/summer-reading-books-cozy/900/700",
    badge: "Miễn phí ship cho đơn từ 200k",
  },
  {
    id: 2,
    eyebrow: "Văn phòng phẩm cao cấp",
    headline: "Nâng tầm\nnghệ thuật viết",
    subtext: "Bút máy, sổ da và dụng cụ viết được tuyển chọn kỹ lưỡng",
    cta: "Xem bộ sưu tập",
    imageUrl: "https://picsum.photos/seed/premium-stationery-desk-flat/900/700",
    badge: "Giảm đến 25% cho đơn đầu tiên",
  },
  {
    id: 3,
    eyebrow: "Quà tặng tinh tế",
    headline: "Món quà ý nghĩa\ncho người thân",
    subtext: "Gói quà miễn phí cho mọi đơn hàng đặc biệt",
    cta: "Chọn quà tặng",
    imageUrl: "https://picsum.photos/seed/gift-books-wrapped-ribbon/900/700",
    badge: "Gói quà miễn phí",
  },
];
