-- ==============================================================================
-- 1. BOOKS SCHEMA UPDATE
-- ==============================================================================
ALTER TABLE public.books
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true,
  ADD COLUMN IF NOT EXISTS is_featured boolean not null default false,
  ADD COLUMN IF NOT EXISTS stock_quantity integer not null default 0,
  ADD COLUMN IF NOT EXISTS low_stock_threshold integer not null default 5,
  ADD COLUMN IF NOT EXISTS admin_note text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now();

-- Add constraints
ALTER TABLE public.books DROP CONSTRAINT IF EXISTS books_stock_quantity_check;
ALTER TABLE public.books ADD CONSTRAINT books_stock_quantity_check CHECK (stock_quantity >= 0);

ALTER TABLE public.books DROP CONSTRAINT IF EXISTS books_low_stock_threshold_check;
ALTER TABLE public.books ADD CONSTRAINT books_low_stock_threshold_check CHECK (low_stock_threshold >= 0);

ALTER TABLE public.books DROP CONSTRAINT IF EXISTS books_price_check;
ALTER TABLE public.books ADD CONSTRAINT books_price_check CHECK (price >= 0);

ALTER TABLE public.books DROP CONSTRAINT IF EXISTS books_original_price_check;
ALTER TABLE public.books ADD CONSTRAINT books_original_price_check CHECK (original_price is null or original_price >= 0);

-- Backfill stock for testing so checkout works
UPDATE public.books SET stock_quantity = 100 WHERE stock_quantity = 0;

-- Indexes
CREATE INDEX IF NOT EXISTS books_is_active_idx ON public.books(is_active);
CREATE INDEX IF NOT EXISTS books_stock_quantity_idx ON public.books(stock_quantity);
CREATE INDEX IF NOT EXISTS books_is_featured_idx ON public.books(is_featured);
CREATE INDEX IF NOT EXISTS books_updated_at_idx ON public.books(updated_at desc);
CREATE INDEX IF NOT EXISTS books_category_idx ON public.books(category);

-- Trigger for books updated_at
CREATE OR REPLACE FUNCTION update_books_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS trg_books_updated_at ON public.books;
CREATE TRIGGER trg_books_updated_at
BEFORE UPDATE ON public.books
FOR EACH ROW
EXECUTE FUNCTION update_books_updated_at();


-- ==============================================================================
-- 2. INVENTORY MOVEMENTS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public.books(id) on delete restrict,
  movement_type text not null,
  quantity_change integer not null,
  quantity_before integer not null,
  quantity_after integer not null,
  reason text not null,
  reference_type text,
  reference_id text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),

  constraint inventory_movements_type_check
    check (
      movement_type in (
        'admin_add',
        'admin_remove',
        'admin_set',
        'order_created',
        'order_cancelled',
        'order_returned',
        'manual_correction'
      )
    ),

  constraint inventory_movements_result_check
    check (
      quantity_before >= 0
      and quantity_after >= 0
    )
);

CREATE INDEX IF NOT EXISTS inventory_movements_book_id_idx ON public.inventory_movements(book_id, created_at desc);
CREATE INDEX IF NOT EXISTS inventory_movements_created_at_idx ON public.inventory_movements(created_at desc);
CREATE INDEX IF NOT EXISTS inventory_movements_created_by_idx ON public.inventory_movements(created_by);

ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can view inventory movements"
ON public.inventory_movements FOR SELECT
TO authenticated USING (public.is_admin());


-- ==============================================================================
-- 3. PRODUCT REVIEWS UPDATE
-- ==============================================================================
ALTER TABLE public.product_reviews
  ADD COLUMN IF NOT EXISTS status text not null default 'published',
  ADD COLUMN IF NOT EXISTS moderation_reason text,
  ADD COLUMN IF NOT EXISTS moderated_by uuid references auth.users(id) on delete set null,
  ADD COLUMN IF NOT EXISTS moderated_at timestamptz;

ALTER TABLE public.product_reviews DROP CONSTRAINT IF EXISTS product_reviews_status_check;
ALTER TABLE public.product_reviews ADD CONSTRAINT product_reviews_status_check CHECK (status in ('published', 'hidden', 'flagged'));

CREATE INDEX IF NOT EXISTS product_reviews_status_idx ON public.product_reviews(status);

-- Update RLS for reviews to only show published to public
DROP POLICY IF EXISTS "Anyone can view product reviews" ON public.product_reviews;
CREATE POLICY "Anyone can view published product reviews"
ON public.product_reviews FOR SELECT
USING (status = 'published');

CREATE POLICY "Users can view their own hidden reviews"
ON public.product_reviews FOR SELECT
TO authenticated USING (user_id = auth.uid() OR public.is_admin());


-- ==============================================================================
-- 4. RPCS: PRODUCT MANAGEMENT
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.admin_update_product(
  p_product_id bigint,
  p_title text,
  p_price numeric,
  p_original_price numeric,
  p_category text,
  p_is_active boolean,
  p_is_featured boolean,
  p_low_stock_threshold integer,
  p_admin_note text
) RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_book record;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Admin access required';
  END IF;

  SELECT * INTO v_book FROM public.books WHERE id = p_product_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Product not found';
  END IF;

  UPDATE public.books
  SET
    title = coalesce(p_title, title),
    price = coalesce(p_price, price),
    original_price = p_original_price,
    category = coalesce(p_category, category),
    is_active = coalesce(p_is_active, is_active),
    is_featured = coalesce(p_is_featured, is_featured),
    low_stock_threshold = coalesce(p_low_stock_threshold, low_stock_threshold),
    admin_note = coalesce(p_admin_note, admin_note)
  WHERE id = p_product_id;

  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, new_data)
  VALUES (v_admin_id, 'product.updated', 'product', p_product_id::text, jsonb_build_object('title', p_title));

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_update_product(bigint, text, numeric, numeric, text, boolean, boolean, integer, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_update_product(bigint, text, numeric, numeric, text, boolean, boolean, integer, text) TO authenticated;


-- ==============================================================================
-- 5. RPCS: INVENTORY MANAGEMENT
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.admin_adjust_inventory(
  p_book_id bigint,
  p_operation text,
  p_quantity integer,
  p_reason text
) RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_book record;
  v_quantity_after integer;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;
  
  IF p_quantity < 0 THEN RAISE EXCEPTION 'Quantity must be positive'; END IF;
  IF length(trim(p_reason)) < 3 THEN RAISE EXCEPTION 'Reason is required'; END IF;

  SELECT * INTO v_book FROM public.books WHERE id = p_book_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Product not found'; END IF;

  IF p_operation = 'add' THEN
    v_quantity_after := v_book.stock_quantity + p_quantity;
  ELSIF p_operation = 'remove' THEN
    v_quantity_after := v_book.stock_quantity - p_quantity;
    IF v_quantity_after < 0 THEN RAISE EXCEPTION 'Cannot remove more stock than available'; END IF;
  ELSIF p_operation = 'set' THEN
    v_quantity_after := p_quantity;
  ELSE
    RAISE EXCEPTION 'Invalid operation';
  END IF;

  UPDATE public.books SET stock_quantity = v_quantity_after WHERE id = p_book_id;

  INSERT INTO public.inventory_movements (
    book_id, movement_type, quantity_change, quantity_before, quantity_after, reason, created_by
  ) VALUES (
    p_book_id, 'admin_' || p_operation,
    CASE WHEN p_operation = 'remove' THEN -p_quantity ELSE p_quantity END,
    v_book.stock_quantity, v_quantity_after, p_reason, v_admin_id
  );

  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, new_data)
  VALUES (v_admin_id, 'inventory.' || p_operation, 'inventory', p_book_id::text, jsonb_build_object('before', v_book.stock_quantity, 'after', v_quantity_after));

  RETURN jsonb_build_object('success', true, 'quantity_after', v_quantity_after);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_adjust_inventory(bigint, text, integer, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_adjust_inventory(bigint, text, integer, text) TO authenticated;


-- ==============================================================================
-- 6. RPCS: REVIEWS MANAGEMENT
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.admin_moderate_review(
  p_review_id bigint,
  p_new_status text,
  p_reason text
) RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_review record;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  IF p_new_status IN ('hidden', 'flagged') AND (p_reason IS NULL OR length(trim(p_reason)) < 3) THEN
    RAISE EXCEPTION 'Reason is required for hiding or flagging';
  END IF;

  SELECT * INTO v_review FROM public.product_reviews WHERE id = p_review_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Review not found'; END IF;

  UPDATE public.product_reviews
  SET status = p_new_status, moderation_reason = p_reason, moderated_by = v_admin_id, moderated_at = now()
  WHERE id = p_review_id;

  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, new_data)
  VALUES (v_admin_id, 'review.' || p_new_status, 'review', p_review_id::text, jsonb_build_object('reason', p_reason));

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_moderate_review(bigint, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_moderate_review(bigint, text, text) TO authenticated;


-- ==============================================================================
-- 7. ATOMIC CHECKOUT WITH INVENTORY
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.create_order_from_cart(
  p_address_id bigint,
  p_items jsonb,
  p_payment_method text,
  p_customer_note text default null,
  p_coupon_code text default null
) RETURNS jsonb AS $$
DECLARE
  v_user_id uuid;
  v_address RECORD;
  v_order_id bigint;
  v_order_code text;
  v_subtotal numeric(14,2) := 0;
  v_shipping_fee numeric(14,2) := 30000;
  v_discount_amount numeric(14,2) := 0;
  v_shipping_discount_amount numeric(14,2) := 0;
  v_total_amount numeric(14,2) := 0;
  v_item record;
  v_book record;
  v_line_total numeric(14,2);
  v_order_status text := 'pending';
  v_payment_status text := 'unpaid';
  v_transfer_content text := null;
  
  v_coupon public.discount_codes;
  v_user_usage_count int;
  v_has_previous_order boolean;
  v_raw_discount numeric(14,2);
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  IF p_payment_method NOT IN ('cod', 'bank_transfer_qr', 'test_payment') THEN RAISE EXCEPTION 'Invalid payment method'; END IF;

  SELECT * INTO v_address FROM public.shipping_addresses WHERE id = p_address_id AND user_id = v_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Shipping address not found or not owned by user'; END IF;

  v_order_code := 'FH-' || to_char(now(), 'YYMMDDHH24MISS') || '-' || upper(substring(md5(random()::text) from 1 for 4));

  FOR v_item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(book_id bigint, quantity int) LOOP
    IF v_item.quantity <= 0 THEN RAISE EXCEPTION 'Quantity must be greater than 0'; END IF;

    -- Lock book for stock check
    SELECT * INTO v_book FROM public.books WHERE id = v_item.book_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Book with ID % not found', v_item.book_id; END IF;
    IF NOT v_book.is_active THEN RAISE EXCEPTION 'Book "%" is currently unavailable', v_book.title; END IF;
    IF v_book.stock_quantity < v_item.quantity THEN RAISE EXCEPTION 'Book "%" is out of stock (Requested: %, Available: %)', v_book.title, v_item.quantity, v_book.stock_quantity; END IF;
    IF v_book.price IS NULL THEN RAISE EXCEPTION 'Book with ID % has no price', v_item.book_id; END IF;

    v_line_total := v_book.price * v_item.quantity;
    v_subtotal := v_subtotal + v_line_total;

    -- Deduct Stock
    UPDATE public.books SET stock_quantity = stock_quantity - v_item.quantity WHERE id = v_item.book_id;
  END LOOP;

  IF v_subtotal >= 200000 THEN v_shipping_fee := 0; END IF;

  IF p_coupon_code IS NOT NULL AND trim(p_coupon_code) != '' THEN
      SELECT * INTO v_coupon FROM public.discount_codes WHERE upper(code) = upper(trim(p_coupon_code)) FOR UPDATE;
      IF NOT FOUND THEN RAISE EXCEPTION 'Mã giảm giá không tồn tại'; END IF;
      IF NOT v_coupon.is_active THEN RAISE EXCEPTION 'Mã giảm giá đã bị khoá'; END IF;
      IF v_coupon.starts_at IS NOT NULL AND now() < v_coupon.starts_at THEN RAISE EXCEPTION 'Mã giảm giá chưa bắt đầu'; END IF;
      IF v_coupon.expires_at IS NOT NULL AND now() > v_coupon.expires_at THEN RAISE EXCEPTION 'Mã giảm giá đã hết hạn'; END IF;
      IF v_subtotal < v_coupon.min_order_amount THEN RAISE EXCEPTION 'Đơn hàng chưa đạt giá trị tối thiểu'; END IF;
      IF v_coupon.usage_limit IS NOT NULL AND v_coupon.current_usage >= v_coupon.usage_limit THEN RAISE EXCEPTION 'Mã giảm giá đã hết lượt sử dụng'; END IF;
      
      SELECT count(*) INTO v_user_usage_count FROM public.discount_code_redemptions WHERE discount_code_id = v_coupon.id AND user_id = v_user_id AND status != 'released';
      IF v_user_usage_count >= v_coupon.usage_limit_per_user THEN RAISE EXCEPTION 'Bạn đã sử dụng hết lượt cho mã này'; END IF;

      IF v_coupon.first_order_only THEN
          SELECT EXISTS(SELECT 1 FROM public.orders WHERE user_id = v_user_id AND status NOT IN ('cancelled')) INTO v_has_previous_order;
          IF v_has_previous_order THEN RAISE EXCEPTION 'Mã chỉ áp dụng cho đơn hàng đầu tiên'; END IF;
      END IF;

      IF v_coupon.discount_type = 'percentage' THEN
          v_raw_discount := v_subtotal * (v_coupon.discount_value / 100.0);
          IF v_coupon.max_discount_amount IS NOT NULL THEN
              v_discount_amount := least(v_raw_discount, v_coupon.max_discount_amount);
          ELSE
              v_discount_amount := v_raw_discount;
          END IF;
      ELSIF v_coupon.discount_type = 'fixed_amount' THEN
          v_discount_amount := least(v_coupon.discount_value, v_subtotal);
      ELSIF v_coupon.discount_type = 'free_shipping' THEN
          v_discount_amount := 0;
          v_shipping_discount_amount := least(v_shipping_fee, v_coupon.discount_value);
      END IF;

      UPDATE public.discount_codes SET current_usage = current_usage + 1 WHERE id = v_coupon.id;
  END IF;

  v_total_amount := v_subtotal + v_shipping_fee - v_discount_amount - v_shipping_discount_amount;
  IF v_total_amount < 0 THEN v_total_amount := 0; END IF;

  IF p_payment_method = 'bank_transfer_qr' THEN v_order_status := 'pending_payment'; v_payment_status := 'awaiting_payment'; v_transfer_content := v_order_code;
  ELSIF p_payment_method = 'cod' THEN v_order_status := 'pending'; v_payment_status := 'unpaid';
  ELSIF p_payment_method = 'test_payment' THEN v_order_status := 'pending_payment'; v_payment_status := 'awaiting_payment'; v_transfer_content := v_order_code; END IF;

  INSERT INTO public.orders (
    order_code, user_id, address_id, status, payment_status, payment_method,
    subtotal, shipping_fee, discount_amount, shipping_discount_amount, total_amount, shipping_address_snapshot, customer_note,
    discount_code_id, discount_code_snapshot, discount_type_snapshot, discount_value_snapshot
  )
  VALUES (
    v_order_code, v_user_id, p_address_id, v_order_status, v_payment_status, p_payment_method,
    v_subtotal, v_shipping_fee, v_discount_amount, v_shipping_discount_amount, v_total_amount,
    jsonb_build_object('recipient_name', v_address.recipient_name, 'phone', v_address.phone, 'address_line', v_address.address_line, 'ward', v_address.ward, 'district', v_address.district, 'province', v_address.province, 'postal_code', v_address.postal_code, 'delivery_note', v_address.delivery_note),
    p_customer_note, (CASE WHEN v_coupon.id IS NOT NULL THEN v_coupon.id ELSE null END), (CASE WHEN v_coupon.id IS NOT NULL THEN v_coupon.code ELSE null END), (CASE WHEN v_coupon.id IS NOT NULL THEN v_coupon.discount_type ELSE null END), (CASE WHEN v_coupon.id IS NOT NULL THEN v_coupon.discount_value ELSE null END)
  )
  RETURNING id INTO v_order_id;

  IF v_coupon.id IS NOT NULL THEN
      INSERT INTO public.discount_code_redemptions (discount_code_id, user_id, order_id, status, discount_amount, shipping_discount_amount) VALUES (v_coupon.id, v_user_id, v_order_id, 'reserved', v_discount_amount, v_shipping_discount_amount);
  END IF;

  FOR v_item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(book_id bigint, quantity int) LOOP
    SELECT * INTO v_book FROM public.books WHERE id = v_item.book_id;
    v_line_total := v_book.price * v_item.quantity;

    INSERT INTO public.order_items (order_id, book_id, source_id, product_title, product_slug, product_image_url, unit_price, original_price, quantity, line_total)
    VALUES (v_order_id, v_book.id, v_book.source_id, v_book.title, v_book.slug, v_book.image_url, v_book.price, v_book.original_price, v_item.quantity, v_line_total);
    
    INSERT INTO public.inventory_movements (book_id, movement_type, quantity_change, quantity_before, quantity_after, reason, reference_type, reference_id, created_by)
    VALUES (v_book.id, 'order_created', -v_item.quantity, v_book.stock_quantity + v_item.quantity, v_book.stock_quantity, 'Order placed', 'order', v_order_id::text, v_user_id);
  END LOOP;

  IF p_payment_method IN ('bank_transfer_qr', 'test_payment') THEN
     INSERT INTO public.payment_transactions (order_id, user_id, payment_method, amount, status, transfer_content) VALUES (v_order_id, v_user_id, p_payment_method, v_total_amount, 'pending', v_transfer_content);
  END IF;

  RETURN jsonb_build_object('order_id', v_order_id, 'order_code', v_order_code, 'total_amount', v_total_amount, 'payment_method', p_payment_method, 'payment_status', v_payment_status, 'status', v_order_status, 'transfer_content', v_transfer_content);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ==============================================================================
-- 8. RPCS: DISCOUNT MANAGEMENT
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.admin_create_discount_code(
  p_code text,
  p_name text,
  p_description text,
  p_discount_type text,
  p_discount_value numeric,
  p_min_order_amount numeric,
  p_max_discount_amount numeric,
  p_usage_limit integer,
  p_usage_limit_per_user integer,
  p_starts_at timestamptz,
  p_expires_at timestamptz,
  p_first_order_only boolean
) RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_code text;
  v_id bigint;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  v_code := upper(trim(p_code));
  
  INSERT INTO public.discount_codes (
    code, name, description, discount_type, discount_value, min_order_amount,
    max_discount_amount, usage_limit, usage_limit_per_user, starts_at, expires_at, first_order_only
  ) VALUES (
    v_code, p_name, p_description, p_discount_type, p_discount_value, p_min_order_amount,
    p_max_discount_amount, p_usage_limit, p_usage_limit_per_user, p_starts_at, p_expires_at, p_first_order_only
  ) RETURNING id INTO v_id;

  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, new_data)
  VALUES (v_admin_id, 'discount.created', 'discount', v_id::text, jsonb_build_object('code', v_code));

  RETURN jsonb_build_object('success', true, 'id', v_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_create_discount_code(text, text, text, text, numeric, numeric, numeric, integer, integer, timestamptz, timestamptz, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_create_discount_code(text, text, text, text, numeric, numeric, numeric, integer, integer, timestamptz, timestamptz, boolean) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_update_discount_code(
  p_id bigint,
  p_code text,
  p_name text,
  p_description text,
  p_discount_type text,
  p_discount_value numeric,
  p_min_order_amount numeric,
  p_max_discount_amount numeric,
  p_usage_limit integer,
  p_usage_limit_per_user integer,
  p_starts_at timestamptz,
  p_expires_at timestamptz,
  p_first_order_only boolean
) RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_code text;
  v_discount record;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  v_code := upper(trim(p_code));

  SELECT * INTO v_discount FROM public.discount_codes WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Discount code not found'; END IF;

  UPDATE public.discount_codes SET
    code = coalesce(v_code, code),
    name = coalesce(p_name, name),
    description = p_description,
    discount_type = coalesce(p_discount_type, discount_type),
    discount_value = coalesce(p_discount_value, discount_value),
    min_order_amount = coalesce(p_min_order_amount, min_order_amount),
    max_discount_amount = p_max_discount_amount,
    usage_limit = p_usage_limit,
    usage_limit_per_user = coalesce(p_usage_limit_per_user, usage_limit_per_user),
    starts_at = p_starts_at,
    expires_at = p_expires_at,
    first_order_only = coalesce(p_first_order_only, first_order_only),
    updated_at = now()
  WHERE id = p_id;

  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, new_data)
  VALUES (v_admin_id, 'discount.updated', 'discount', p_id::text, jsonb_build_object('code', v_code));

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_update_discount_code(bigint, text, text, text, text, numeric, numeric, numeric, integer, integer, timestamptz, timestamptz, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_update_discount_code(bigint, text, text, text, text, numeric, numeric, numeric, integer, integer, timestamptz, timestamptz, boolean) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_set_discount_active(
  p_id bigint,
  p_is_active boolean
) RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_discount record;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  SELECT * INTO v_discount FROM public.discount_codes WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Discount code not found'; END IF;

  UPDATE public.discount_codes SET is_active = p_is_active, updated_at = now() WHERE id = p_id;

  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, new_data)
  VALUES (v_admin_id, CASE WHEN p_is_active THEN 'discount.activated' ELSE 'discount.deactivated' END, 'discount', p_id::text, jsonb_build_object('is_active', p_is_active));

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_set_discount_active(bigint, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_set_discount_active(bigint, boolean) TO authenticated;

