-- ==============================================================================
-- 1. CONTACT MESSAGES TABLE
-- ==============================================================================
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  email text not null,
  phone text,
  subject text not null,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now(),

  constraint contact_messages_status_check
    check (status in ('new', 'in_progress', 'resolved', 'spam'))
);

-- RLS cho contact_messages
alter table public.contact_messages enable row level security;

-- Admin có thể select/update
create policy "Admins can view contact_messages"
  on public.contact_messages for select
  using (public.has_admin_permission('support.manage') = true);

create policy "Admins can update contact_messages"
  on public.contact_messages for update
  using (public.has_admin_permission('support.manage') = true);

-- RPC để submit contact message an toàn từ Client
create or replace function public.submit_contact_message(
  p_full_name text,
  p_email text,
  p_phone text,
  p_subject text,
  p_message text
) returns jsonb as $$
declare
  v_user_id uuid;
  v_id bigint;
begin
  -- Validate basic
  if length(trim(p_full_name)) < 2 then raise exception 'Tên không hợp lệ'; end if;
  if length(trim(p_email)) < 5 or p_email not like '%@%' then raise exception 'Email không hợp lệ'; end if;
  if length(trim(p_message)) < 10 then raise exception 'Nội dung quá ngắn'; end if;

  v_user_id := auth.uid();

  insert into public.contact_messages (user_id, full_name, email, phone, subject, message, status)
  values (v_user_id, trim(p_full_name), trim(p_email), trim(p_phone), trim(p_subject), trim(p_message), 'new')
  returning id into v_id;

  return jsonb_build_object('success', true, 'id', v_id);
end;
$$ language plpgsql security definer set search_path = public;

-- ==============================================================================
-- 2. BLOG POSTS TABLE
-- ==============================================================================
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null,
  excerpt text,
  content text not null,
  cover_image_url text,
  author_name text,
  status text not null default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint blog_posts_status_check
    check (status in ('draft', 'published', 'archived'))
);

create unique index if not exists blog_posts_slug_uidx on public.blog_posts(slug);

-- RLS cho blog_posts
alter table public.blog_posts enable row level security;

-- Public read access for published posts
create policy "Public can view published blog_posts"
  on public.blog_posts for select
  using (status = 'published');

-- Admin read/write
create policy "Admins can manage blog_posts"
  on public.blog_posts for all
  using (public.has_admin_permission('blog.manage') = true);
