-- ==============================================================================
-- MIGRATION: ADMIN MVP & PROFILES
-- ==============================================================================

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_role_check check (role in ('user', 'admin'))
);

CREATE INDEX IF NOT EXISTS profiles_role_idx ON public.profiles(role);
CREATE INDEX IF NOT EXISTS profiles_is_active_idx ON public.profiles(is_active);

-- Trigger for updated_at on profiles
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile"
ON public.profiles FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile (except role and is_active)"
ON public.profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (
  auth.uid() = id AND 
  role = (SELECT role FROM public.profiles WHERE id = auth.uid()) AND
  is_active = (SELECT is_active FROM public.profiles WHERE id = auth.uid())
);

-- 2. TRIGGER FOR NEW USERS
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, is_active)
  VALUES (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    'user',
    true
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Backfill existing users
INSERT INTO public.profiles (id, full_name, role, is_active)
SELECT 
  id, 
  coalesce(raw_user_meta_data ->> 'full_name', ''), 
  'user', 
  true
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- 3. IS_ADMIN() FUNCTION
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin' AND is_active = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 4. ADMIN RLS POLICIES FOR EXISTING TABLES
-- Orders
DROP POLICY IF EXISTS "Admins can view all orders" ON public.orders;
CREATE POLICY "Admins can view all orders"
ON public.orders FOR SELECT
TO authenticated
USING (public.is_admin());

-- Order Items
DROP POLICY IF EXISTS "Admins can view all order items" ON public.order_items;
CREATE POLICY "Admins can view all order items"
ON public.order_items FOR SELECT
TO authenticated
USING (public.is_admin());

-- Payment Transactions
DROP POLICY IF EXISTS "Admins can view all payment transactions" ON public.payment_transactions;
CREATE POLICY "Admins can view all payment transactions"
ON public.payment_transactions FOR SELECT
TO authenticated
USING (public.is_admin());

-- Profiles
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
CREATE POLICY "Admins can view all profiles"
ON public.profiles FOR SELECT
TO authenticated
USING (public.is_admin());

-- 5. ADMIN AUDIT LOGS & ORDER HISTORY
CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb,
  created_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS admin_audit_logs_admin_id_idx ON public.admin_audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS admin_audit_logs_entity_idx ON public.admin_audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS admin_audit_logs_created_at_idx ON public.admin_audit_logs(created_at desc);

ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can view audit logs"
ON public.admin_audit_logs FOR SELECT
TO authenticated
USING (public.is_admin());


CREATE TABLE IF NOT EXISTS public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  changed_by uuid references auth.users(id) on delete set null,
  old_status text,
  new_status text not null,
  note text,
  created_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS order_status_history_order_id_idx ON public.order_status_history(order_id);
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their order history"
ON public.order_status_history FOR SELECT
TO authenticated
USING (
  order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid()) OR public.is_admin()
);

-- 6. RPC: ADMIN_UPDATE_ORDER_STATUS
CREATE OR REPLACE FUNCTION public.admin_update_order_status(
  p_order_id bigint,
  p_new_status text,
  p_note text DEFAULT NULL
)
RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_order record;
  v_old_status text;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Admin access required';
  END IF;

  -- Lock order
  SELECT * INTO v_order FROM public.orders WHERE id = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found';
  END IF;

  v_old_status := v_order.status;

  IF v_old_status IN ('delivered', 'cancelled') THEN
    RAISE EXCEPTION 'Order cannot be updated from final status';
  END IF;

  IF p_new_status NOT IN ('pending_payment', 'pending', 'confirmed', 'processing', 'shipping', 'delivered', 'cancelled') THEN
    RAISE EXCEPTION 'Invalid status';
  END IF;

  -- Update order
  UPDATE public.orders
  SET 
    status = p_new_status,
    confirmed_at = CASE WHEN p_new_status = 'confirmed' AND confirmed_at IS NULL THEN now() ELSE confirmed_at END,
    shipped_at = CASE WHEN p_new_status = 'shipping' AND shipped_at IS NULL THEN now() ELSE shipped_at END,
    delivered_at = CASE WHEN p_new_status = 'delivered' AND delivered_at IS NULL THEN now() ELSE delivered_at END,
    cancelled_at = CASE WHEN p_new_status = 'cancelled' AND cancelled_at IS NULL THEN now() ELSE cancelled_at END
  WHERE id = p_order_id;

  -- Log history
  INSERT INTO public.order_status_history (order_id, changed_by, old_status, new_status, note)
  VALUES (p_order_id, v_admin_id, v_old_status, p_new_status, p_note);

  -- Audit log
  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, old_data, new_data)
  VALUES (
    v_admin_id, 
    'order.status_updated', 
    'order', 
    p_order_id::text, 
    jsonb_build_object('status', v_old_status), 
    jsonb_build_object('status', p_new_status, 'note', p_note)
  );

  RETURN jsonb_build_object('success', true, 'new_status', p_new_status);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_update_order_status(bigint, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_update_order_status(bigint, text, text) TO authenticated;

-- 7. RPC: ADMIN_UPDATE_PAYMENT_STATUS
CREATE OR REPLACE FUNCTION public.admin_update_payment_status(
  p_order_id bigint,
  p_new_status text,
  p_note text DEFAULT NULL
)
RETURNS jsonb AS $$
DECLARE
  v_admin_id uuid;
  v_order record;
  v_old_status text;
BEGIN
  v_admin_id := auth.uid();
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Admin access required';
  END IF;

  IF p_new_status NOT IN ('unpaid', 'awaiting_payment', 'paid', 'failed', 'refunded') THEN
    RAISE EXCEPTION 'Invalid payment status';
  END IF;

  SELECT * INTO v_order FROM public.orders WHERE id = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order not found';
  END IF;

  v_old_status := v_order.payment_status;
  IF v_old_status = p_new_status THEN
    RETURN jsonb_build_object('success', true, 'message', 'Status unchanged');
  END IF;

  UPDATE public.orders
  SET 
    payment_status = p_new_status,
    paid_at = CASE WHEN p_new_status = 'paid' AND paid_at IS NULL THEN now() ELSE paid_at END
  WHERE id = p_order_id;

  -- Update transactions if relevant
  IF p_new_status = 'paid' THEN
    UPDATE public.payment_transactions
    SET status = 'paid', paid_at = now()
    WHERE order_id = p_order_id AND status = 'pending';
  ELSIF p_new_status = 'failed' THEN
    UPDATE public.payment_transactions
    SET status = 'failed'
    WHERE order_id = p_order_id AND status = 'pending';
  END IF;

  -- Audit log
  INSERT INTO public.admin_audit_logs (admin_id, action, entity_type, entity_id, old_data, new_data)
  VALUES (
    v_admin_id, 
    'payment.status_updated', 
    'order', 
    p_order_id::text, 
    jsonb_build_object('payment_status', v_old_status), 
    jsonb_build_object('payment_status', p_new_status, 'note', p_note)
  );

  RETURN jsonb_build_object('success', true, 'new_status', p_new_status);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.admin_update_payment_status(bigint, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_update_payment_status(bigint, text, text) TO authenticated;
