-- ==============================================================================
-- 1. EXTEND PROFILES
-- ==============================================================================
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS blocked_reason text,
  ADD COLUMN IF NOT EXISTS blocked_at timestamptz,
  ADD COLUMN IF NOT EXISTS blocked_by uuid references auth.users(id) on delete set null,
  ADD COLUMN IF NOT EXISTS last_order_at timestamptz;

-- ==============================================================================
-- 2. CUSTOMER ADMIN NOTES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.customer_admin_notes (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references auth.users(id) on delete cascade,
  admin_id uuid references auth.users(id) on delete set null,
  note text not null,
  created_at timestamptz not null default now(),
  constraint customer_admin_notes_length_check check (char_length(note) between 1 and 2000)
);

CREATE INDEX IF NOT EXISTS customer_admin_notes_customer_idx ON public.customer_admin_notes(customer_id, created_at desc);

ALTER TABLE public.customer_admin_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can view customer notes" ON public.customer_admin_notes FOR SELECT TO authenticated USING (public.is_admin());

-- ==============================================================================
-- 3. RBAC TABLES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.admin_roles (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  description text,
  is_system boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

CREATE UNIQUE INDEX IF NOT EXISTS admin_roles_code_upper_uidx ON public.admin_roles(upper(code));

CREATE TABLE IF NOT EXISTS public.admin_permissions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  module text not null,
  created_at timestamptz not null default now()
);

CREATE TABLE IF NOT EXISTS public.admin_role_permissions (
  role_id bigint not null references public.admin_roles(id) on delete cascade,
  permission_id bigint not null references public.admin_permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS admin_role_permissions_role_idx ON public.admin_role_permissions(role_id);

CREATE TABLE IF NOT EXISTS public.admin_user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.admin_roles(id) on delete cascade,
  assigned_by uuid references auth.users(id) on delete set null,
  assigned_at timestamptz not null default now(),
  is_active boolean not null default true,
  primary key (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS admin_user_roles_active_idx ON public.admin_user_roles(user_id, is_active);

ALTER TABLE public.admin_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_user_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view roles" ON public.admin_roles FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "Admins can view permissions" ON public.admin_permissions FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "Admins can view role_permissions" ON public.admin_role_permissions FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "Admins can view user_roles" ON public.admin_user_roles FOR SELECT TO authenticated USING (public.is_admin());

-- ==============================================================================
-- 4. RBAC FUNCTIONS
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.has_admin_permission(p_permission_code text)
RETURNS boolean AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_has_permission boolean;
  v_is_super boolean;
BEGIN
  -- 1. Check if user is active
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = v_uid AND is_active = true) THEN
    RETURN false;
  END IF;

  -- 2. Check if user is super_admin
  SELECT EXISTS (
    SELECT 1 FROM public.admin_user_roles ur
    JOIN public.admin_roles r ON ur.role_id = r.id
    WHERE ur.user_id = v_uid AND ur.is_active = true AND r.is_active = true AND upper(r.code) = 'SUPER_ADMIN'
  ) INTO v_is_super;

  IF v_is_super THEN RETURN true; END IF;

  -- 3. Check specific permission
  SELECT EXISTS (
    SELECT 1 FROM public.admin_user_roles ur
    JOIN public.admin_roles r ON ur.role_id = r.id
    JOIN public.admin_role_permissions rp ON r.id = rp.role_id
    JOIN public.admin_permissions p ON rp.permission_id = p.id
    WHERE ur.user_id = v_uid 
      AND ur.is_active = true 
      AND r.is_active = true 
      AND p.code = p_permission_code
  ) INTO v_has_permission;

  RETURN v_has_permission;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean AS $$
BEGIN
  RETURN public.has_admin_permission('system.super_admin'); -- super admin logic is handled inside
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ==============================================================================
-- 5. SEED RBAC
-- ==============================================================================
-- 5.1 Seed Permissions
INSERT INTO public.admin_permissions (code, name, module) VALUES
('dashboard.view', 'Xem Dashboard', 'Dashboard'),
('orders.view', 'Xem Đơn hàng', 'Orders'),
('orders.status.update', 'Cập nhật trạng thái đơn', 'Orders'),
('orders.notes.create', 'Ghi chú đơn hàng', 'Orders'),
('payments.view', 'Xem Thanh toán', 'Payments'),
('payments.status.update', 'Cập nhật thanh toán', 'Payments'),
('products.view', 'Xem Sản phẩm', 'Catalog'),
('products.update', 'Sửa Sản phẩm', 'Catalog'),
('products.visibility.manage', 'Ẩn/hiện Sản phẩm', 'Catalog'),
('inventory.view', 'Xem Tồn kho', 'Catalog'),
('inventory.adjust', 'Điều chỉnh Tồn kho', 'Catalog'),
('discounts.view', 'Xem Mã giảm giá', 'Marketing'),
('discounts.create', 'Tạo Mã giảm giá', 'Marketing'),
('discounts.update', 'Sửa Mã giảm giá', 'Marketing'),
('discounts.status.manage', 'Bật/tắt Mã giảm giá', 'Marketing'),
('reviews.view', 'Xem Đánh giá', 'Marketing'),
('reviews.moderate', 'Kiểm duyệt Đánh giá', 'Marketing'),
('customers.view', 'Xem Khách hàng', 'Customers'),
('customers.notes.view', 'Xem Ghi chú khách hàng', 'Customers'),
('customers.notes.create', 'Tạo Ghi chú khách hàng', 'Customers'),
('customers.status.manage', 'Khóa/Mở khóa Khách hàng', 'Customers'),
('staff.view', 'Xem Nhân sự', 'System'),
('staff.manage', 'Quản lý Nhân sự', 'System'),
('roles.view', 'Xem Vai trò', 'System'),
('roles.manage', 'Quản lý Vai trò', 'System'),
('analytics.view', 'Xem Thống kê', 'Analytics'),
('reports.view', 'Xem Báo cáo', 'Analytics'),
('reports.export', 'Xuất dữ liệu', 'Analytics'),
('shipping.view', 'Xem Cấu hình vận chuyển', 'Shipping'),
('shipping.manage', 'Quản lý Vận chuyển', 'Shipping'),
('audit.view', 'Xem Nhật ký hoạt động', 'System')
ON CONFLICT (code) DO NOTHING;

-- 5.2 Seed Roles
INSERT INTO public.admin_roles (code, name, is_system, is_active) VALUES
('super_admin', 'Quản trị viên tối cao', true, true),
('operations_manager', 'Quản lý vận hành', true, true),
('catalog_manager', 'Quản lý danh mục', true, true),
('marketing_manager', 'Quản lý marketing', true, true),
('customer_support', 'Chăm sóc khách hàng', true, true),
('analyst', 'Chuyên viên phân tích', true, true)
ON CONFLICT (upper(code)) DO NOTHING;

-- 5.3 Map Permissions to Roles (except super_admin which has all by logic)
-- Operations Manager
INSERT INTO public.admin_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM public.admin_roles r, public.admin_permissions p
WHERE r.code = 'operations_manager' 
AND p.code IN ('dashboard.view', 'orders.view', 'orders.status.update', 'orders.notes.create', 'payments.view', 'payments.status.update', 'customers.view', 'customers.notes.view', 'customers.notes.create', 'shipping.view', 'analytics.view')
ON CONFLICT DO NOTHING;

-- Catalog Manager
INSERT INTO public.admin_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM public.admin_roles r, public.admin_permissions p
WHERE r.code = 'catalog_manager' 
AND p.code IN ('dashboard.view', 'products.view', 'products.update', 'products.visibility.manage', 'inventory.view', 'inventory.adjust', 'reviews.view')
ON CONFLICT DO NOTHING;

-- Marketing Manager
INSERT INTO public.admin_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM public.admin_roles r, public.admin_permissions p
WHERE r.code = 'marketing_manager' 
AND p.code IN ('dashboard.view', 'discounts.view', 'discounts.create', 'discounts.update', 'discounts.status.manage', 'reviews.view', 'reviews.moderate', 'analytics.view', 'reports.view')
ON CONFLICT DO NOTHING;

-- Customer Support
INSERT INTO public.admin_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM public.admin_roles r, public.admin_permissions p
WHERE r.code = 'customer_support' 
AND p.code IN ('dashboard.view', 'orders.view', 'orders.notes.create', 'customers.view', 'customers.notes.view', 'customers.notes.create', 'reviews.view')
ON CONFLICT DO NOTHING;

-- Analyst
INSERT INTO public.admin_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM public.admin_roles r, public.admin_permissions p
WHERE r.code = 'analyst' 
AND p.code IN ('dashboard.view', 'analytics.view', 'reports.view', 'reports.export')
ON CONFLICT DO NOTHING;

-- 5.4 Migrate Existing Admins to Super Admin
INSERT INTO public.admin_user_roles (user_id, role_id, is_active)
SELECT p.id, r.id, true
FROM public.profiles p, public.admin_roles r
WHERE p.role = 'admin' AND r.code = 'super_admin'
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- 6. SHIPPING TABLES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.shipping_zones (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  description text,
  priority integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

CREATE UNIQUE INDEX IF NOT EXISTS shipping_zones_code_upper_uidx ON public.shipping_zones(upper(code));

CREATE TABLE IF NOT EXISTS public.shipping_zone_locations (
  id bigint generated by default as identity primary key,
  zone_id bigint not null references public.shipping_zones(id) on delete cascade,
  province text not null,
  district text,
  created_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS shipping_zone_locations_lookup_idx ON public.shipping_zone_locations(province, district);

CREATE TABLE IF NOT EXISTS public.shipping_methods (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  description text,
  min_delivery_days integer,
  max_delivery_days integer,
  supports_cod boolean not null default true,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shipping_methods_days_check check (
    min_delivery_days is null or max_delivery_days is null or (min_delivery_days >= 0 and max_delivery_days >= min_delivery_days)
  )
);

CREATE TABLE IF NOT EXISTS public.shipping_rates (
  id bigint generated by default as identity primary key,
  zone_id bigint not null references public.shipping_zones(id) on delete cascade,
  method_id bigint not null references public.shipping_methods(id) on delete cascade,
  base_fee numeric not null default 0,
  free_shipping_threshold numeric,
  min_order_amount numeric,
  max_order_amount numeric,
  is_active boolean not null default true,
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shipping_rates_base_fee_check check (base_fee >= 0),
  constraint shipping_rates_threshold_check check (free_shipping_threshold is null or free_shipping_threshold >= 0)
);

CREATE INDEX IF NOT EXISTS shipping_rates_lookup_idx ON public.shipping_rates(zone_id, method_id, is_active);

-- Seed basic shipping zone "Toàn quốc"
INSERT INTO public.shipping_zones (code, name, priority) VALUES ('TOAN_QUOC', 'Toàn quốc', 0) ON CONFLICT (upper(code)) DO NOTHING;
INSERT INTO public.shipping_methods (code, name, min_delivery_days, max_delivery_days, supports_cod) VALUES ('STANDARD', 'Giao hàng tiêu chuẩn', 2, 5, true) ON CONFLICT DO NOTHING;

-- Seed rate to make checkout work (Standard Toàn quốc = 30k)
INSERT INTO public.shipping_rates (zone_id, method_id, base_fee, free_shipping_threshold)
SELECT z.id, m.id, 30000, 500000 
FROM public.shipping_zones z, public.shipping_methods m
WHERE z.code = 'TOAN_QUOC' AND m.code = 'STANDARD'
ON CONFLICT DO NOTHING;

-- Add shipping snapshot to orders
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS shipping_method_id bigint references public.shipping_methods(id) on delete set null,
  ADD COLUMN IF NOT EXISTS shipping_method_code text,
  ADD COLUMN IF NOT EXISTS shipping_method_name text,
  ADD COLUMN IF NOT EXISTS shipping_zone_id bigint references public.shipping_zones(id) on delete set null,
  ADD COLUMN IF NOT EXISTS shipping_zone_name text,
  ADD COLUMN IF NOT EXISTS estimated_delivery_min_days integer,
  ADD COLUMN IF NOT EXISTS estimated_delivery_max_days integer;

-- ==============================================================================
-- 7. UPDATE CHECKOUT RPC TO USE SERVER SHIPPING
-- ==============================================================================
DROP FUNCTION IF EXISTS public.create_order_from_cart(uuid, bigint, jsonb, text, text);

CREATE OR REPLACE FUNCTION public.create_order_from_cart(
  p_user_id uuid,
  p_address_id bigint,
  p_cart_items jsonb, -- array of { book_id, quantity }
  p_payment_method text,
  p_discount_code text DEFAULT NULL,
  p_shipping_method_id bigint DEFAULT NULL
)
RETURNS jsonb AS $$
DECLARE
  v_address record;
  v_zone_id bigint;
  v_zone_name text;
  v_rate record;
  v_method record;
  v_shipping_fee numeric := 0;
  v_subtotal numeric := 0;
  v_discount_amount numeric := 0;
  v_shipping_discount_amount numeric := 0;
  v_total_amount numeric := 0;
  v_order_code text;
  v_order_id bigint;
  v_discount record;
  v_item record;
  v_book record;
BEGIN
  -- 1. Check Address & User
  SELECT * INTO v_address FROM public.shipping_addresses WHERE id = p_address_id AND user_id = p_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Address not found or does not belong to user'; END IF;

  -- 2. Determine Zone
  -- Tries to find matching province/district, falls back to 'TOAN_QUOC'
  SELECT z.id, z.name INTO v_zone_id, v_zone_name
  FROM public.shipping_zone_locations l
  JOIN public.shipping_zones z ON l.zone_id = z.id
  WHERE z.is_active = true 
    AND lower(l.province) = lower(v_address.province)
    AND (l.district IS NULL OR lower(l.district) = lower(v_address.district))
  ORDER BY z.priority DESC, l.district NULLS LAST
  LIMIT 1;

  IF v_zone_id IS NULL THEN
    SELECT id, name INTO v_zone_id, v_zone_name FROM public.shipping_zones WHERE code = 'TOAN_QUOC' AND is_active = true LIMIT 1;
    IF v_zone_id IS NULL THEN RAISE EXCEPTION 'No shipping zone found'; END IF;
  END IF;

  -- 3. Determine Shipping Rate
  IF p_shipping_method_id IS NOT NULL THEN
    SELECT m.id, m.code, m.name, m.min_delivery_days, m.max_delivery_days, m.supports_cod, r.base_fee, r.free_shipping_threshold
    INTO v_rate
    FROM public.shipping_rates r
    JOIN public.shipping_methods m ON r.method_id = m.id
    WHERE r.zone_id = v_zone_id AND m.id = p_shipping_method_id AND r.is_active = true AND m.is_active = true
      AND (r.starts_at IS NULL OR r.starts_at <= now())
      AND (r.expires_at IS NULL OR r.expires_at >= now())
    LIMIT 1;

    IF NOT FOUND THEN RAISE EXCEPTION 'Shipping method not available for this address'; END IF;
  ELSE
    -- Default to standard
    SELECT m.id, m.code, m.name, m.min_delivery_days, m.max_delivery_days, m.supports_cod, r.base_fee, r.free_shipping_threshold
    INTO v_rate
    FROM public.shipping_rates r
    JOIN public.shipping_methods m ON r.method_id = m.id
    WHERE r.zone_id = v_zone_id AND r.is_active = true AND m.is_active = true
      AND (r.starts_at IS NULL OR r.starts_at <= now())
      AND (r.expires_at IS NULL OR r.expires_at >= now())
    ORDER BY r.base_fee ASC LIMIT 1;

    IF NOT FOUND THEN RAISE EXCEPTION 'No shipping methods available for this address'; END IF;
  END IF;

  IF p_payment_method = 'cod' AND NOT v_rate.supports_cod THEN
    RAISE EXCEPTION 'Shipping method does not support COD';
  END IF;

  -- 4. Calculate subtotal & lock items
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_cart_items)
  LOOP
    SELECT id, title, price, stock_quantity, is_active INTO v_book 
    FROM public.books WHERE id = (v_item.value->>'book_id')::bigint FOR UPDATE;

    IF NOT FOUND OR NOT v_book.is_active THEN RAISE EXCEPTION 'Product % is not available', v_item.value->>'book_id'; END IF;
    IF v_book.stock_quantity < (v_item.value->>'quantity')::integer THEN RAISE EXCEPTION 'Not enough stock for %', v_book.title; END IF;

    v_subtotal := v_subtotal + (v_book.price * (v_item.value->>'quantity')::integer);
  END LOOP;

  -- 5. Calculate Shipping Fee
  v_shipping_fee := v_rate.base_fee;
  IF v_rate.free_shipping_threshold IS NOT NULL AND v_subtotal >= v_rate.free_shipping_threshold THEN
    v_shipping_fee := 0;
  END IF;

  -- 6. Check Discount
  IF p_discount_code IS NOT NULL THEN
    SELECT * INTO v_discount FROM public.discount_codes 
    WHERE code = p_discount_code AND is_active = true 
      AND (starts_at IS NULL OR starts_at <= now())
      AND (expires_at IS NULL OR expires_at >= now())
    FOR UPDATE;

    IF FOUND THEN
      IF v_discount.usage_limit IS NOT NULL AND v_discount.current_usage >= v_discount.usage_limit THEN
        RAISE EXCEPTION 'Discount code usage limit reached';
      END IF;
      IF v_discount.min_order_amount IS NOT NULL AND v_subtotal < v_discount.min_order_amount THEN
        RAISE EXCEPTION 'Order amount does not meet discount minimum';
      END IF;

      IF v_discount.discount_type = 'percentage' THEN
        v_discount_amount := least(v_subtotal * (v_discount.discount_value / 100.0), COALESCE(v_discount.max_discount_amount, 999999999));
      ELSIF v_discount.discount_type = 'fixed_amount' THEN
        v_discount_amount := least(v_discount.discount_value, v_subtotal);
      ELSIF v_discount.discount_type = 'free_shipping' THEN
        v_shipping_discount_amount := v_shipping_fee;
        v_shipping_fee := 0;
      END IF;
    ELSE
      RAISE EXCEPTION 'Invalid discount code';
    END IF;
  END IF;

  v_total_amount := v_subtotal + v_shipping_fee - v_discount_amount;
  IF v_total_amount < 0 THEN v_total_amount := 0; END IF;

  v_order_code := 'ORD' || to_char(now(), 'YYYYMMDD') || lpad(floor(random() * 1000000)::text, 6, '0');

  -- 7. Create Order
  INSERT INTO public.orders (
    order_code, user_id, status, payment_status, payment_method, 
    subtotal_amount, shipping_fee, discount_amount, shipping_discount_amount, total_amount,
    shipping_name, shipping_phone, shipping_address_line, shipping_ward, shipping_district, shipping_province,
    shipping_method_id, shipping_method_code, shipping_method_name, shipping_zone_id, shipping_zone_name,
    estimated_delivery_min_days, estimated_delivery_max_days
  ) VALUES (
    v_order_code, p_user_id, 'pending', 'unpaid', p_payment_method,
    v_subtotal, v_shipping_fee, v_discount_amount, v_shipping_discount_amount, v_total_amount,
    v_address.full_name, v_address.phone, v_address.address_line, v_address.ward, v_address.district, v_address.province,
    v_rate.id, v_rate.code, v_rate.name, v_zone_id, v_zone_name,
    v_rate.min_delivery_days, v_rate.max_delivery_days
  ) RETURNING id INTO v_order_id;

  -- 8. Create Order Items & Deduct Stock
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_cart_items)
  LOOP
    SELECT * INTO v_book FROM public.books WHERE id = (v_item.value->>'book_id')::bigint;
    
    INSERT INTO public.order_items (order_id, book_id, product_name, quantity, unit_price, line_total)
    VALUES (v_order_id, v_book.id, v_book.title, (v_item.value->>'quantity')::integer, v_book.price, v_book.price * (v_item.value->>'quantity')::integer);

    UPDATE public.books SET stock_quantity = stock_quantity - (v_item.value->>'quantity')::integer WHERE id = v_book.id;

    INSERT INTO public.inventory_movements (book_id, movement_type, quantity_change, quantity_after, reason)
    VALUES (v_book.id, 'out', -1 * (v_item.value->>'quantity')::integer, v_book.stock_quantity - (v_item.value->>'quantity')::integer, 'Order ' || v_order_code);
  END LOOP;

  -- 9. Handle Discount Redemption
  IF v_discount IS NOT NULL THEN
    UPDATE public.discount_codes SET current_usage = current_usage + 1 WHERE id = v_discount.id;
    INSERT INTO public.discount_code_redemptions (discount_code_id, user_id, order_id, discount_amount, shipping_discount_amount)
    VALUES (v_discount.id, p_user_id, v_order_id, v_discount_amount, v_shipping_discount_amount);
  END IF;

  -- 10. Update last order
  UPDATE public.profiles SET last_order_at = now() WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true, 'order_id', v_order_id, 'order_code', v_order_code, 'total_amount', v_total_amount);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.create_order_from_cart(uuid, bigint, jsonb, text, text, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_order_from_cart(uuid, bigint, jsonb, text, text, bigint) TO authenticated;

-- ==============================================================================
-- 8. ANALYTICS & RBAC RPCS
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.admin_get_dashboard_analytics(p_start_date date, p_end_date date)
RETURNS jsonb AS $$
DECLARE
  v_revenue numeric;
  v_orders integer;
  v_delivered integer;
  v_customers integer;
BEGIN
  IF NOT public.has_admin_permission('analytics.view') THEN
    RAISE EXCEPTION 'Admin analytics permission required';
  END IF;

  SELECT coalesce(sum(total_amount), 0) INTO v_revenue
  FROM public.orders
  WHERE payment_status = 'paid' AND status != 'cancelled' 
    AND created_at >= p_start_date AND created_at < p_end_date + interval '1 day';

  SELECT count(id) INTO v_orders
  FROM public.orders
  WHERE status != 'cancelled' 
    AND created_at >= p_start_date AND created_at < p_end_date + interval '1 day';

  SELECT count(id) INTO v_delivered
  FROM public.orders
  WHERE status = 'delivered' 
    AND created_at >= p_start_date AND created_at < p_end_date + interval '1 day';

  SELECT count(distinct user_id) INTO v_customers
  FROM public.orders
  WHERE created_at >= p_start_date AND created_at < p_end_date + interval '1 day';

  RETURN jsonb_build_object(
    'revenue', v_revenue,
    'orders', v_orders,
    'delivered', v_delivered,
    'customers', v_customers
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
